sudo: required
dist: trusty
language: python
python:
- '2.7'
virtualenv:
  system_site_packages: true
cache: apt
before_install:
- sudo apt-get --purge remove mongodb-10gen postgresql-9.2 postgresql-contrib-9.2
  postgresql-9.3 postgresql-contrib-9.3
- export ROS_DISTRO=indigo
- export ROS_CI_DESKTOP=`lsb_release -cs`
- export ROS_MASTER_URI=http://localhost:11311
notifications:
  email: false
  slack:
    secure: JGeguBqm109fIuTAKnM8Noap8sOB2Fv5md/ISalosEFgGfpA4i8q5ebK6nXe05e7muSrtxxJIYzNkoJoe+S9wEVoD3VOWmGgIRA5b5GuQqak3uYSWlYFfAyOVZkvihgIljlFrQTMxm9KEz4eoh3+a1iU75bv3bGerTPAg+/8l/RcGDAT8bChSb565rS0L1mRIKni6MxBL9Fy4wuhVANaG/2K4k3FXP2Kc5S/Vsurp55H5MTrFVyN737AMGZl7MkIsbRfwN/WPZS62aJHpfdT+k//2a5loruCDr8mDjYKnFLrO0vkFjgkSLNOrNLc+BG3Ebj6vy/35laLLJc2krSgvdhIElHv08tTCgzCZZSM8cOeI3s3HaX/HlxpyoO1zIfXLIC28KO81cd6Qr5fIoffN13VMhNgxbZj/CmoifUiq9Lp2ljWEiNvjKnSuAuu+Lfdd4YHHHqfZESjM+cSB4BT0VGGuEYWEtWo8aM30uI+OL0aUaYWf3crtqTSmmLG8ZncUj3ATbIiFfJR/vXz0ZL2U71f8aTrh8V8gS5fNNdXlGZAS2BYRyc0kZr962g9sFXz34wSpXNTpuUzH6YCaQfkYNUJSsczD0jT4uJXcDkFSD7Z5OCfLxObiLc1xeg7qCZ7VN9drkfmrIGnfmXBBM9UbXSuoe5hbztK7iK1VBCNMxE=
install:
- echo "deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main" | sudo tee /etc/apt/sources.list.d/ros-latest.list
- wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
- sudo apt-get update -qq
- sudo apt-get install -qq -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin
  ros-$ROS_DISTRO-ros
- sudo apt-get install -qq -y mongodb ros-$ROS_DISTRO-warehouse-ros
- sudo apt-get install -qq -y ros-$ROS_DISTRO-moveit-*
- sudo pip install -U setuptools
- sudo pip install -U catkin_tools
- source /opt/ros/$ROS_DISTRO/setup.bash
- sudo rosdep init
- rosdep update
- mkdir -p ~/catkin_ws/src
- cd ..; mv code_it_fetch ~/catkin_ws/src
- cd ~/catkin_ws/src
- git clone https://github.com/hcrlab/blinky.git
- git clone https://github.com/hcrlab/code_it_msgs.git
- git clone https://github.com/jstnhuang/mongo_msg_db.git
- git clone https://github.com/jstnhuang/mongo_msg_db_msgs.git
- git clone https://github.com/jstnhuang/rapid.git
- git clone https://github.com/jstnhuang/stf.git
- catkin_init_workspace
- cd ~/catkin_ws/
- rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y -q
- cd ~/catkin_ws/
- catkin build code_it_fetch
